### ISSUE TITLE
Error on cbar_mode in demos/3_Multichannel/01_Colour_Processing

### ISSUE THREAD

**Issue by Letizia97** [vais-ral/CIL-Demos#116]
In demos/3_Multichannel/01_Colour_Processing, the AxesGrid function is called with input parameter cbar_mode='None', which gives the error  " 'None' is not a valid value for cbar_mode". It should be called with cbar_mode=None.

**Comment by lauramurgatroyd** [comment]
Closed by https://github.com/TomographicImaging/CIL-Demos/pull/118
