### ISSUE TITLE
Which python version is good to test CIL library?

### ISSUE THREAD

**Issue by TianSong1991** [vais-ral/CIL-Demos#127]
The CIL module is a very good module, please tell me, which version of python is used to test all the tests of this module library, I am currently using version 3.10, and found that there are many other dependent module libraries that do not support it, please Tell me what is the stable test python version, thank you very much for replying to me while helping.

**Comment by paskino** [comment]
Hi @TianSong1991 

CIL is [currently built and tested](https://github.com/TomographicImaging/CIL/blob/12e45d329a5c8011a3dd30c533ad536d36ac185d/recipe/conda_build_config.yaml#L22-L25) with python 3.8, 3.9 and 3.10 on linux and Windows. Python 3.11 will be supported soon.

Hopefully this helps. Do not hesitate to reopen the issue, if you find that my reply has not solved it.

**Comment by TianSong1991** [comment]
> 

Thank you for your replying. Python version 3.10 is ok.
