### ISSUE TITLE
SPDHG explicit demo probabilities 

### ISSUE THREAD

**Issue by MargaretDuff** [vais-ral/CIL-Demos#128]
https://github.com/TomographicImaging/CIL-Demos/blob/affca76da8a46973d1ca2d823b4d206a6f1bbd33/demos/2_Iterative/04_SPDHG.ipynb#L500

In the explicit demo for SPDHG you explain the non-uniform sampling: half of the time, we update the dual variable corresponding to TV, so that $p_{n+1}=1/2$, and half of the time we update one of the dual variable corresponding to one subset, so that $p_i=1/(2n)$ for $1\leq i \leq n$. 

You also define it in line https://github.com/TomographicImaging/CIL-Demos/blob/affca76da8a46973d1ca2d823b4d206a6f1bbd33/demos/2_Iterative/04_SPDHG.ipynb#L497 but then don't use it in either line https://github.com/TomographicImaging/CIL-Demos/blob/affca76da8a46973d1ca2d823b4d206a6f1bbd33/demos/2_Iterative/04_SPDHG.ipynb#L500 or line https://github.com/TomographicImaging/CIL-Demos/blob/affca76da8a46973d1ca2d823b4d206a6f1bbd33/demos/2_Iterative/04_SPDHG.ipynb#L581. 

Just needs a quick fix to add "prob=prob" to the calls to SPDHG.

**Comment by lauramurgatroyd** [comment]
Looks like this has now been done? Can we close @MargaretDuff ?

**Comment by MargaretDuff** [comment]
Yep - can be closed!
