### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by RasmiaKulan** [vais-ral/CIL-Demos#145]
The link in `03_where_is_my_reader` Exercise C: Create the geometry is broken (leads to error 404 -  File not found)
![image](https://github.com/TomographicImaging/CIL-Demos/assets/69144386/6e287dd4-d459-4b13-9dc7-72bc4a34b4c9)

**Comment by lauramurgatroyd** [comment]
https://tomographicimaging.github.io/CIL/nightly/framework/#cone2d-geometry-fanbeam is what should be linked
