### ISSUE TITLE
Update to CIL version 24.2 (latest release)

### ISSUE THREAD

**Issue by paskino** [vais-ral/CIL-Demos#155]
Also check 
- https://github.com/TomographicImaging/CIL/pull/1826
- Update demos for changes with CIL >= [v24.2.0](https://github.com/TomographicImaging/CIL/blob/v24.2.0/CHANGELOG.md)
- All notebooks with iterative algorithms, check different API, e.g. use of `max_iterations` and `run`
- `CGLS` removed `tolerance`
- `GC` and `Armijo` rule

Notebooks working correctly with latest [release](https://github.com/TomographicImaging/CIL/releases):
- [x] 1_Introduction @hrobarts #162 
  + [x] 05_usb_limited_angle_fbp_sirt.ipynb
- [x] 2 @MargaretDuff
- [x] 3_Multichannel @casperdcl #160

**Comment by MargaretDuff** [comment]
In 2.01 notebook we have an issue with not enough iterations for Armijio rule: 
![image](https://github.com/user-attachments/assets/729be4ed-439d-4229-9fcc-18027b9fc275)

**Comment by MargaretDuff** [comment]
In 2.01 nothing is showing for me when an algorithm is run: 
![image](https://github.com/user-attachments/assets/534153e0-092e-4f9d-b5d8-8e27bbfb0efb)

**Comment by MargaretDuff** [comment]
In 2.01 we shouldn't be using max_iterations 
![image](https://github.com/user-attachments/assets/4a413364-2135-4bf4-85f8-1c01957a9cc6)

**Comment by hrobarts** [comment]
We should also remove max_iteration in FBP_CGLS_SIRT.ipynb

![image](https://github.com/user-attachments/assets/18e1fcba-fe13-42cf-b3d8-ad8d2d707e0e)

Should change the second cell to run with a large number of iterations to demonstrate it stopping running when the tolerance is reached.

**Comment by MargaretDuff** [comment]
Notebook 2.3 - Check what we want to do with the non-negativity constraint 
![image](https://github.com/user-attachments/assets/6805d319-4d78-4a84-aa4d-b713b487ad4f)

**Comment by hrobarts** [comment]
Also add iterations in colab/CIL_colab.ipynb

![image](https://github.com/user-attachments/assets/22f07a01-9fb3-4817-a399-160d4fe27021)

**Comment by jakobsj** [comment]
I've come across the issues of notebook 2.01 when testing with CIL version 24 ahead of teaching next week. Are fixes being worked on and planned for release before that? Or suggested any work-arounds on e.g. the Armijo issue and max_iteration, other than running on v23 instead?

**Comment by MargaretDuff** [comment]
Hi @jakobsj - I thought we set you up on the cloud with version 23.1.1. which is tested on the current notebooks? 

We are planning a push to update the notebooks but won't be done by the training course next week. 

R.e. the armijio rule in 2.01. If you pass `alpha = 1e8` to the gradient descent set-up, that should work.
 
`max_iterations` should just give you a warning which can be ignored. Importantly, in version 24 you need to pass a number of iterations to `algo.run`, you can't just use `algo.run()`

**Comment by jakobsj** [comment]
We did, yes and that seems to work fine.  In parallel we are testing a local solution with an environment with all other libraries needed for processing in the remainder of the week and so far CIL v24 had been installed and there were some difficulties downgrading to 23, but not sure if they can be resolved.

Thanks for the suggestion of passing alpha=1e8, it seems to run more step size loops but still fail on that system. Same with 1e10, 1e12, so not sure.

Passing `max_iterations` causes an error for me, whereas `algo.run()` with a number runs with a warning.

**Comment by jakobsj** [comment]
*Without  a number (of iterations) runs with a warning.

**Comment by MargaretDuff** [comment]
The other option for the armijio rule is just to run a smaller number of algorithm iterations. It should only be having issues as it gets close to convergence. 

It should still run with `max_iteration` it shouldn't fail with an error - can I check that you have `max_iteration` without the `s`? (sorry I made a typo in my response)

**Comment by hrobarts** [comment]
In colab/CIL_Colab.ipynb I get this error
![image](https://github.com/user-attachments/assets/1c272be3-71a4-4a00-bda3-d4d5583687ab)

**Comment by hrobarts** [comment]
> In colab/CIL_Colab.ipynb I get this error ![image](https://private-user-images.githubusercontent.com/77114597/359981474-1c272be3-71a4-4a00-bda3-d4d5583687ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTQ2MzEsIm5iZiI6MTcyNDI1NDMzMSwicGF0aCI6Ii83NzExNDU5Ny8zNTk5ODE0NzQtMWMyNzJiZTMtNzFhNC00YTAwLWJkYTMtZDRkNTU4MzY4N2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE1MzIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YjVkNDQyNjZhZmEzZGMxNjQyODgzMzJjY2JhNjhlNjUyNjJlYWFjNWFhOTBkZmE2NjU4YWY0YmU3NjU0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9vZ8jMiaIMHK3mN-PGAFxD8qe2R0Q2KJio_WaW62IUs)

Actually I was using the wrong version of the regularisation toolkit, now it's fine

**Comment by MargaretDuff** [comment]
> 
> Thanks for the suggestion of passing alpha=1e8, it seems to run more step size loops but still fail on that system. Same with 1e10, 1e12, so not sure.
> 
Could I also check that you restart the algorithm with each try? i.e. if you change alpha, re-run the cell above that resets gradient descent and the cell which runs 200 iterations. Otherwise you are running many many iterations

**Comment by MargaretDuff** [comment]
To do update 24.1.0:
Folder 1: @hrobarts 
Folder 2: @MargaretDuff 
Folder 3: @casperdcl 

@MargaretDuff to discuss with @hrobarts about CGLS

**Comment by lauramurgatroyd** [comment]
Editing the title of this as all of the updates we did for v24.1 are working on v24.2
