### ISSUE TITLE
Broken link to 'Binner' documentation page in 02_preprocessing_seeds_conebeam.ipynb

### ISSUE THREAD

**Issue by M-A-Demir** [vais-ral/CIL-Demos#166]
In the file: CIL-Demos/demos/1_Introduction/exercises/02_preprocessing_seeds_conebeam.ipynb
At 'Exercise G: Binning Data', there is a link to the CIL docs to setup a Binner processor, but the link brings up a 404 error.

Broken link: https://tomographicimaging.github.io/CIL/nightly/processors.html?highlight=binner#cil.processors.Binner

Non-broken link: https://tomographicimaging.github.io/CIL/nightly/processors/#data-binner

**Comment by lauramurgatroyd** [comment]
Thanks for pointing this out! If you're comfortable doing so, feel free to open a PR correcting this, or if not we'll sort it!
