### ISSUE TITLE
Rename files consistently, remove unused files

### ISSUE THREAD

**Issue by jakobsj** [vais-ral/CIL-Demos#31]
Can we rename all notebooks and solutions to start with XX_[exercise name].ipynb, for XX = 00, 01, 02, 03, 04, 05?

Same name for solutions just with "_solutions" at the end before .ipynb, not at beginning of filename.

Any files to remove/move elsewhere (like template pdhg_S_1000.nexus)?

**Comment by rwarr95** [comment]
pdhg_S_1000.nxs is used in my notebooks. It can be moved elsewhere but I will probably need to change the directory in my notebooks.

**Comment by jakobsj** [comment]
Let's just leave it there for now then.
