### ISSUE TITLE
Origin of Walnut dataset is not listed

### ISSUE THREAD

**Issue by paskino** [vais-ral/CIL-Demos#56]
It's not in the [notebook ](https://github.com/TomographicImaging/CIL-Demos/blob/main/examples/1_Introduction/01_intro_walnut_conebeam.ipynb)nor in the [additional info](https://github.com/TomographicImaging/CIL-Demos/blob/main/examples/1_Introduction/additional_exercises_data_resources.ipynb) in the introduction week.

**Comment by paskino** [comment]
It is linked in the [README](https://github.com/TomographicImaging/CIL-Demos/blob/main/examples/README.md) but requires people to look in multiple locations.

https://zenodo.org/record/4822516

**Comment by lauramurgatroyd** [comment]
closed by https://github.com/TomographicImaging/CIL-Demos/pull/97
