### ISSUE TITLE
show_2D warning in 02_intro_sandstone_parallel_roi.ipynb

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CIL-Demos#66]
![image](https://user-images.githubusercontent.com/60604372/164748662-8dc01bf9-0496-43ed-b0ca-579507a4bdf3.png)

**Comment by lauramurgatroyd** [comment]
Also in 03_preprocessing cell [28]

**Comment by lauramurgatroyd** [comment]
And [9] in 04_FBP_CGLS_SIRT

**Comment by lauramurgatroyd** [comment]
Also in 01_into_walnut - cell [13]

**Comment by gfardell** [comment]
closed in CIL. Notebooks will be fixed in next CIL release. https://github.com/TomographicImaging/CIL/issues/1353
