### ISSUE TITLE
Week 3, 01 Colour Processing

### ISSUE THREAD

**Issue by epapoutsellis** [vais-ral/CIL-Demos#68]
- Font type `'FreeSerifBold.ttf` cannot be found from the system, use `DejaVuSerif.ttf` instead
- Replace `mask = ig.subset(channel=0).allocate(True,dtype=np.bool)` by mask = `ig.subset(channel=0).allocate()`

**Comment by lauramurgatroyd** [comment]
updating these now

**Comment by epapoutsellis** [comment]
I created also #69 , but will close it approve #77

**Comment by lauramurgatroyd** [comment]
sorry I got confused, didn't realise you had fixed it!
