### ISSUE TITLE
Incorrect number of angles selected in Week2/03_PDHG.ipynb

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CIL-Demos#71]
The description says that 160 angles are selected:
https://github.com/TomographicImaging/CIL-Demos/blob/1d68391111ce617786416b1a1730f0331ba9c9fd/training/2021_Fully3D/Week2/03_PDHG.ipynb?short_path=4aa4bae#L298

But when the acquisition geometry is printed, it shows there are 161 angles

**Comment by epapoutsellis** [comment]
closed by #74
