### ISSUE TITLE
Too many prints in algorithm runs in examples/2_Iterative/01_optimisation_gd_fista.ipynb

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CIL-Demos#73]
When the algorithms are run, every single step is printed and there are hundreds of steps. Is this expected and is it necessary?

It means the notebook gets really full of all of the prints and it is hard to scroll up and compare different images.
![image](https://user-images.githubusercontent.com/60604372/165079098-00f91359-d95c-420a-9b23-9b66a94c4b55.png)

Further down in the notebook it runs `myPDHG.run(5000,verbose=2)` and all 5000 steps are printed.

I wonder if less prints would speed it up a bit? It took me over 30 mins to run this notebook.

**Comment by gfardell** [comment]
fixed with v22 work
