### ISSUE TITLE
Updated demos for cil v22.0.0

### ISSUE THREAD

**Issue by gfardell** [vais-ral/CIL-Demos#86]
- all demos should run on v22.0.0
- readme instructions

**Comment by gfardell** [comment]
All in a v22 branch, before merge tag demos of v21?

**Comment by lauramurgatroyd** [comment]
v22 branch is here: https://github.com/TomographicImaging/CIL-Demos/tree/v22. All PRs for updating the notebooks should be made to that branch.
I am going to look at the notebooks in the 1_Introduction folder.

- [x] 0
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] additional data

**Comment by gfardell** [comment]
I'll start on 2_Iterative

- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [x] 5

Note: updating 5 - Laminography to use `tigre` and recon class

**Comment by lauramurgatroyd** [comment]
I think @jakobsj mentioned on discord that he would look at the 2nd folder

**Comment by gfardell** [comment]
PR to v22_all (sorry!)

**Comment by lauramurgatroyd** [comment]
https://github.com/TomographicImaging/CIL-Demos/tree/v22_all
